../subjects/md5sum.fast  /usr/bin/[
../subjects/md5sum.fast  /usr/bin/2to3
../subjects/md5sum.fast  /usr/bin/2to3-2.7
../subjects/md5sum.fast  /usr/bin/2to3-3.5
../subjects/md5sum.fast  /usr/bin/aa-enabled
../subjects/md5sum.fast  /usr/bin/aclocal
../subjects/md5sum.fast  /usr/bin/aclocal-1.15
../subjects/md5sum.fast  /usr/bin/acpibin
../subjects/md5sum.fast  /usr/bin/acpidump
../subjects/md5sum.fast  /usr/bin/acpidump-acpica
../subjects/md5sum.fast  /usr/bin/acpiexec
../subjects/md5sum.fast  /usr/bin/acpihelp
../subjects/md5sum.fast  /usr/bin/acpi_listen
../subjects/md5sum.fast  /usr/bin/acpinames
../subjects/md5sum.fast  /usr/bin/acpisrc
../subjects/md5sum.fast  /usr/bin/acpixtract
../subjects/md5sum.fast  /usr/bin/acpixtract-acpica
../subjects/md5sum.fast  /usr/bin/add-apt-repository
../subjects/md5sum.fast  /usr/bin/addpart
../subjects/md5sum.fast  /usr/bin/addr2line
../subjects/md5sum.fast  /usr/bin/alien
../subjects/md5sum.fast  /usr/bin/ant
../subjects/md5sum.fast  /usr/bin/apg
../subjects/md5sum.fast  /usr/bin/apgbfm
../subjects/md5sum.fast  /usr/bin/appletviewer
../subjects/md5sum.fast  /usr/bin/apport-bug
../subjects/md5sum.fast  /usr/bin/apport-cli
../subjects/md5sum.fast  /usr/bin/apport-collect
../subjects/md5sum.fast  /usr/bin/apport-unpack
../subjects/md5sum.fast  /usr/bin/appres
../subjects/md5sum.fast  /usr/bin/apropos
../subjects/md5sum.fast  /usr/bin/apt
../subjects/md5sum.fast  /usr/bin/apt-add-repository
../subjects/md5sum.fast  /usr/bin/apt-cache
../subjects/md5sum.fast  /usr/bin/apt-cdrom
../subjects/md5sum.fast  /usr/bin/apt-config
../subjects/md5sum.fast  /usr/bin/aptdcon
../subjects/md5sum.fast  /usr/bin/apt-extracttemplates
../subjects/md5sum.fast  /usr/bin/apt-file
../subjects/md5sum.fast  /usr/bin/apt-ftparchive
../subjects/md5sum.fast  /usr/bin/apt-get
../subjects/md5sum.fast  /usr/bin/apt-key
../subjects/md5sum.fast  /usr/bin/apt-mark
../subjects/md5sum.fast  /usr/bin/apt-sortpkgs
../subjects/md5sum.fast  /usr/bin/ar
../subjects/md5sum.fast  /usr/bin/arch
../subjects/md5sum.fast  /usr/bin/arping
../subjects/md5sum.fast  /usr/bin/as
../subjects/md5sum.fast  /usr/bin/aspell
../subjects/md5sum.fast  /usr/bin/aspell-import
../subjects/md5sum.fast  /usr/bin/at
../subjects/md5sum.fast  /usr/bin/atq
../subjects/md5sum.fast  /usr/bin/atrm
../subjects/md5sum.fast  /usr/bin/attr
../subjects/md5sum.fast  /usr/bin/autoconf
../subjects/md5sum.fast  /usr/bin/autoheader
../subjects/md5sum.fast  /usr/bin/autom4te
../subjects/md5sum.fast  /usr/bin/automake
../subjects/md5sum.fast  /usr/bin/automake-1.15
../subjects/md5sum.fast  /usr/bin/autopoint
../subjects/md5sum.fast  /usr/bin/autoreconf
../subjects/md5sum.fast  /usr/bin/autoscan
../subjects/md5sum.fast  /usr/bin/autoupdate
../subjects/md5sum.fast  /usr/bin/avahi-browse
../subjects/md5sum.fast  /usr/bin/avahi-browse-domains
../subjects/md5sum.fast  /usr/bin/avahi-publish
../subjects/md5sum.fast  /usr/bin/avahi-publish-address
../subjects/md5sum.fast  /usr/bin/avahi-publish-service
../subjects/md5sum.fast  /usr/bin/avahi-resolve
../subjects/md5sum.fast  /usr/bin/avahi-resolve-address
../subjects/md5sum.fast  /usr/bin/avahi-resolve-host-name
../subjects/md5sum.fast  /usr/bin/avahi-set-host-name
../subjects/md5sum.fast  /usr/bin/awk
../subjects/md5sum.fast  /usr/bin/base32
../subjects/md5sum.fast  /usr/bin/base64
../subjects/md5sum.fast  /usr/bin/basename
../subjects/md5sum.fast  /usr/bin/bashbug
../subjects/md5sum.fast  /usr/bin/batch
../subjects/md5sum.fast  /usr/bin/bc
../subjects/md5sum.fast  /usr/bin/bccmd
../subjects/md5sum.fast  /usr/bin/bdftopcf
../subjects/md5sum.fast  /usr/bin/bdftruncate
../subjects/md5sum.fast  /usr/bin/bison
../subjects/md5sum.fast  /usr/bin/bison.yacc
../subjects/md5sum.fast  /usr/bin/bluemoon
../subjects/md5sum.fast  /usr/bin/bluetoothctl
../subjects/md5sum.fast  /usr/bin/bluetooth-sendto
../subjects/md5sum.fast  /usr/bin/bluetooth-wizard
../subjects/md5sum.fast  /usr/bin/bootctl
../subjects/md5sum.fast  /usr/bin/broadwayd
../subjects/md5sum.fast  /usr/bin/bsd-from
../subjects/md5sum.fast  /usr/bin/bsd-write
../subjects/md5sum.fast  /usr/bin/btattach
../subjects/md5sum.fast  /usr/bin/btmgmt
../subjects/md5sum.fast  /usr/bin/btmon
../subjects/md5sum.fast  /usr/bin/bugpoint-3.3
../subjects/md5sum.fast  /usr/bin/busctl
../subjects/md5sum.fast  /usr/bin/byobu
../subjects/md5sum.fast  /usr/bin/byobu-config
../subjects/md5sum.fast  /usr/bin/byobu-ctrl-a
../subjects/md5sum.fast  /usr/bin/byobu-disable
../subjects/md5sum.fast  /usr/bin/byobu-disable-prompt
../subjects/md5sum.fast  /usr/bin/byobu-enable
../subjects/md5sum.fast  /usr/bin/byobu-enable-prompt
../subjects/md5sum.fast  /usr/bin/byobu-export
../subjects/md5sum.fast  /usr/bin/byobu-janitor
../subjects/md5sum.fast  /usr/bin/byobu-keybindings
../subjects/md5sum.fast  /usr/bin/byobu-launch
../subjects/md5sum.fast  /usr/bin/byobu-launcher
../subjects/md5sum.fast  /usr/bin/byobu-launcher-install
../subjects/md5sum.fast  /usr/bin/byobu-launcher-uninstall
../subjects/md5sum.fast  /usr/bin/byobu-layout
../subjects/md5sum.fast  /usr/bin/byobu-prompt
../subjects/md5sum.fast  /usr/bin/byobu-quiet
../subjects/md5sum.fast  /usr/bin/byobu-reconnect-sockets
../subjects/md5sum.fast  /usr/bin/byobu-screen
../subjects/md5sum.fast  /usr/bin/byobu-select-backend
../subjects/md5sum.fast  /usr/bin/byobu-select-profile
../subjects/md5sum.fast  /usr/bin/byobu-select-session
../subjects/md5sum.fast  /usr/bin/byobu-shell
../subjects/md5sum.fast  /usr/bin/byobu-silent
../subjects/md5sum.fast  /usr/bin/byobu-status
../subjects/md5sum.fast  /usr/bin/byobu-status-detail
../subjects/md5sum.fast  /usr/bin/byobu-tmux
../subjects/md5sum.fast  /usr/bin/byobu-ugraph
../subjects/md5sum.fast  /usr/bin/byobu-ulevel
../subjects/md5sum.fast  /usr/bin/c++
../subjects/md5sum.fast  /usr/bin/c2ph
../subjects/md5sum.fast  /usr/bin/c89
../subjects/md5sum.fast  /usr/bin/c89-gcc
../subjects/md5sum.fast  /usr/bin/c99
../subjects/md5sum.fast  /usr/bin/c99-gcc
../subjects/md5sum.fast  /usr/bin/cal
../subjects/md5sum.fast  /usr/bin/calendar
../subjects/md5sum.fast  /usr/bin/captoinfo
../subjects/md5sum.fast  /usr/bin/catchsegv
../subjects/md5sum.fast  /usr/bin/catman
../subjects/md5sum.fast  /usr/bin/cautious-launcher
../subjects/md5sum.fast  /usr/bin/cc
../subjects/md5sum.fast  /usr/bin/cd-create-profile
../subjects/md5sum.fast  /usr/bin/cd-fix-profile
../subjects/md5sum.fast  /usr/bin/cd-iccdump
../subjects/md5sum.fast  /usr/bin/cd-it8
../subjects/md5sum.fast  /usr/bin/c++filt
../subjects/md5sum.fast  /usr/bin/cgroupfs-mount
../subjects/md5sum.fast  /usr/bin/cgroupfs-umount
../subjects/md5sum.fast  /usr/bin/chacl
../subjects/md5sum.fast  /usr/bin/chage
../subjects/md5sum.fast  /usr/bin/chardet3
../subjects/md5sum.fast  /usr/bin/chardetect3
../subjects/md5sum.fast  /usr/bin/chattr
../subjects/md5sum.fast  /usr/bin/chcon
../subjects/md5sum.fast  /usr/bin/check-language-support
../subjects/md5sum.fast  /usr/bin/chfn
../subjects/md5sum.fast  /usr/bin/chrt
../subjects/md5sum.fast  /usr/bin/chsh
../subjects/md5sum.fast  /usr/bin/cifscreds
../subjects/md5sum.fast  /usr/bin/cifsdd
../subjects/md5sum.fast  /usr/bin/cifsiostat
../subjects/md5sum.fast  /usr/bin/ciptool
../subjects/md5sum.fast  /usr/bin/ckbcomp
../subjects/md5sum.fast  /usr/bin/cksum
../subjects/md5sum.fast  /usr/bin/clang++-libc++
../subjects/md5sum.fast  /usr/bin/clear
../subjects/md5sum.fast  /usr/bin/clear_console
../subjects/md5sum.fast  /usr/bin/clusterdb
../subjects/md5sum.fast  /usr/bin/cmake
../subjects/md5sum.fast  /usr/bin/cmp
../subjects/md5sum.fast  /usr/bin/codepage
../subjects/md5sum.fast  /usr/bin/col
../subjects/md5sum.fast  /usr/bin/col1
../subjects/md5sum.fast  /usr/bin/col2
../subjects/md5sum.fast  /usr/bin/col3
../subjects/md5sum.fast  /usr/bin/col4
../subjects/md5sum.fast  /usr/bin/col5
../subjects/md5sum.fast  /usr/bin/col6
../subjects/md5sum.fast  /usr/bin/col7
../subjects/md5sum.fast  /usr/bin/col8
../subjects/md5sum.fast  /usr/bin/col9
../subjects/md5sum.fast  /usr/bin/colcrt
../subjects/md5sum.fast  /usr/bin/colormgr
../subjects/md5sum.fast  /usr/bin/colrm
../subjects/md5sum.fast  /usr/bin/column
../subjects/md5sum.fast  /usr/bin/combinediff
../subjects/md5sum.fast  /usr/bin/comm
../subjects/md5sum.fast  /usr/bin/compose
../subjects/md5sum.fast  /usr/bin/containerd
../subjects/md5sum.fast  /usr/bin/containerd-shim
../subjects/md5sum.fast  /usr/bin/containerd-shim-runc-v1
../subjects/md5sum.fast  /usr/bin/containerd-stress
../subjects/md5sum.fast  /usr/bin/convert-dtsv0
../subjects/md5sum.fast  /usr/bin/corelist
../subjects/md5sum.fast  /usr/bin/cpack
../subjects/md5sum.fast  /usr/bin/cpan
../subjects/md5sum.fast  /usr/bin/cpan5.22-x86_64-linux-gnu
../subjects/md5sum.fast  /usr/bin/cpp
../subjects/md5sum.fast  /usr/bin/cpp-3.4
../subjects/md5sum.fast  /usr/bin/cpp-4.4
../subjects/md5sum.fast  /usr/bin/cpp-4.7
../subjects/md5sum.fast  /usr/bin/cpp-5
../subjects/md5sum.fast  /usr/bin/cpupower
../subjects/md5sum.fast  /usr/bin/crc32
../subjects/md5sum.fast  /usr/bin/createdb
../subjects/md5sum.fast  /usr/bin/createlang
../subjects/md5sum.fast  /usr/bin/createuser
../subjects/md5sum.fast  /usr/bin/credentials-preferences
../subjects/md5sum.fast  /usr/bin/c_rehash
../subjects/md5sum.fast  /usr/bin/crontab
../subjects/md5sum.fast  /usr/bin/csplit
../subjects/md5sum.fast  /usr/bin/ctail
../subjects/md5sum.fast  /usr/bin/ctest
../subjects/md5sum.fast  /usr/bin/ctr
../subjects/md5sum.fast  /usr/bin/ctstat
../subjects/md5sum.fast  /usr/bin/curl
../subjects/md5sum.fast  /usr/bin/curl-config
../subjects/md5sum.fast  /usr/bin/cut
../subjects/md5sum.fast  /usr/bin/cvt
../subjects/md5sum.fast  /usr/bin/dbus-cleanup-sockets
../subjects/md5sum.fast  /usr/bin/dbus-daemon
../subjects/md5sum.fast  /usr/bin/dbus-launch
../subjects/md5sum.fast  /usr/bin/dbus-monitor
../subjects/md5sum.fast  /usr/bin/dbus-run-session
../subjects/md5sum.fast  /usr/bin/dbus-send
../subjects/md5sum.fast  /usr/bin/dbus-update-activation-environment
../subjects/md5sum.fast  /usr/bin/dbus-uuidgen
../subjects/md5sum.fast  /usr/bin/dbwrap_tool
../subjects/md5sum.fast  /usr/bin/dconf
../subjects/md5sum.fast  /usr/bin/deallocvt
../subjects/md5sum.fast  /usr/bin/debconf
../subjects/md5sum.fast  /usr/bin/debconf-apt-progress
../subjects/md5sum.fast  /usr/bin/debconf-communicate
../subjects/md5sum.fast  /usr/bin/debconf-copydb
../subjects/md5sum.fast  /usr/bin/debconf-escape
../subjects/md5sum.fast  /usr/bin/debconf-gettextize
../subjects/md5sum.fast  /usr/bin/debconf-set-selections
../subjects/md5sum.fast  /usr/bin/debconf-show
../subjects/md5sum.fast  /usr/bin/debconf-updatepo
../subjects/md5sum.fast  /usr/bin/deb-systemd-helper
../subjects/md5sum.fast  /usr/bin/deb-systemd-invoke
../subjects/md5sum.fast  /usr/bin/debugedit
../subjects/md5sum.fast  /usr/bin/dehtmldiff
../subjects/md5sum.fast  /usr/bin/delpart
../subjects/md5sum.fast  /usr/bin/desktop-file-edit
../subjects/md5sum.fast  /usr/bin/desktop-file-install
../subjects/md5sum.fast  /usr/bin/desktop-file-validate
../subjects/md5sum.fast  /usr/bin/devdump
../subjects/md5sum.fast  /usr/bin/dh
../subjects/md5sum.fast  /usr/bin/dh_auto_build
../subjects/md5sum.fast  /usr/bin/dh_auto_clean
../subjects/md5sum.fast  /usr/bin/dh_auto_configure
../subjects/md5sum.fast  /usr/bin/dh_auto_install
../subjects/md5sum.fast  /usr/bin/dh_auto_test
../subjects/md5sum.fast  /usr/bin/dh_autotools-dev_restoreconfig
../subjects/md5sum.fast  /usr/bin/dh_autotools-dev_updateconfig
../subjects/md5sum.fast  /usr/bin/dh_bash-completion
../subjects/md5sum.fast  /usr/bin/dh_bugfiles
../subjects/md5sum.fast  /usr/bin/dh_builddeb
../subjects/md5sum.fast  /usr/bin/dh_clean
../subjects/md5sum.fast  /usr/bin/dh_compress
../subjects/md5sum.fast  /usr/bin/dh_desktop
../subjects/md5sum.fast  /usr/bin/dh_fixperms
../subjects/md5sum.fast  /usr/bin/dh_gconf
../subjects/md5sum.fast  /usr/bin/dh_gencontrol
../subjects/md5sum.fast  /usr/bin/dh_icons
../subjects/md5sum.fast  /usr/bin/dh_install
../subjects/md5sum.fast  /usr/bin/dh_installcatalogs
../subjects/md5sum.fast  /usr/bin/dh_installchangelogs
../subjects/md5sum.fast  /usr/bin/dh_installcron
../subjects/md5sum.fast  /usr/bin/dh_installdeb
../subjects/md5sum.fast  /usr/bin/dh_installdebconf
../subjects/md5sum.fast  /usr/bin/dh_installdirs
../subjects/md5sum.fast  /usr/bin/dh_installdocs
../subjects/md5sum.fast  /usr/bin/dh_installemacsen
../subjects/md5sum.fast  /usr/bin/dh_installexamples
../subjects/md5sum.fast  /usr/bin/dh_installgsettings
../subjects/md5sum.fast  /usr/bin/dh_installifupdown
../subjects/md5sum.fast  /usr/bin/dh_installinfo
../subjects/md5sum.fast  /usr/bin/dh_installinit
../subjects/md5sum.fast  /usr/bin/dh_installlogcheck
../subjects/md5sum.fast  /usr/bin/dh_installlogrotate
../subjects/md5sum.fast  /usr/bin/dh_installman
../subjects/md5sum.fast  /usr/bin/dh_installmanpages
../subjects/md5sum.fast  /usr/bin/dh_installmenu
../subjects/md5sum.fast  /usr/bin/dh_installmime
../subjects/md5sum.fast  /usr/bin/dh_installmodules
../subjects/md5sum.fast  /usr/bin/dh_installpam
../subjects/md5sum.fast  /usr/bin/dh_installppp
../subjects/md5sum.fast  /usr/bin/dh_installtex
../subjects/md5sum.fast  /usr/bin/dh_installudev
../subjects/md5sum.fast  /usr/bin/dh_installwm
../subjects/md5sum.fast  /usr/bin/dh_installxfonts
../subjects/md5sum.fast  /usr/bin/dh_installxmlcatalogs
../subjects/md5sum.fast  /usr/bin/dh_link
../subjects/md5sum.fast  /usr/bin/dh_lintian
../subjects/md5sum.fast  /usr/bin/dh_listpackages
../subjects/md5sum.fast  /usr/bin/dh_makeshlibs
../subjects/md5sum.fast  /usr/bin/dh_md5sums
../subjects/md5sum.fast  /usr/bin/dh_movefiles
../subjects/md5sum.fast  /usr/bin/dh_perl
../subjects/md5sum.fast  /usr/bin/dh_prep
../subjects/md5sum.fast  /usr/bin/dh_pypy
../subjects/md5sum.fast  /usr/bin/dh_python2
../subjects/md5sum.fast  /usr/bin/dh_python3
../subjects/md5sum.fast  /usr/bin/dh_python-ply
../subjects/md5sum.fast  /usr/bin/dh_scrollkeeper
../subjects/md5sum.fast  /usr/bin/dh_shlibdeps
../subjects/md5sum.fast  /usr/bin/dh_strip
../subjects/md5sum.fast  /usr/bin/dh_strip_nondeterminism
../subjects/md5sum.fast  /usr/bin/dh_suidregister
../subjects/md5sum.fast  /usr/bin/dh_testdir
../subjects/md5sum.fast  /usr/bin/dh_testroot
../subjects/md5sum.fast  /usr/bin/dh_ucf
../subjects/md5sum.fast  /usr/bin/dh_undocumented
../subjects/md5sum.fast  /usr/bin/dh_update_autotools_config
../subjects/md5sum.fast  /usr/bin/dh_usrlocal
../subjects/md5sum.fast  /usr/bin/diff
../subjects/md5sum.fast  /usr/bin/diff3
../subjects/md5sum.fast  /usr/bin/diffindex-download
../subjects/md5sum.fast  /usr/bin/diffindex-rred
../subjects/md5sum.fast  /usr/bin/diffstat
../subjects/md5sum.fast  /usr/bin/dig
../subjects/md5sum.fast  /usr/bin/dircolors
../subjects/md5sum.fast  /usr/bin/dirmngr
../subjects/md5sum.fast  /usr/bin/dirmngr-client
../subjects/md5sum.fast  /usr/bin/dirname
../subjects/md5sum.fast  /usr/bin/dirsplit
../subjects/md5sum.fast  /usr/bin/discover-config
../subjects/md5sum.fast  /usr/bin/dm-tool
../subjects/md5sum.fast  /usr/bin/docker
../subjects/md5sum.fast  /usr/bin/dockerd
../subjects/md5sum.fast  /usr/bin/docker-init
../subjects/md5sum.fast  /usr/bin/docker-proxy
../subjects/md5sum.fast  /usr/bin/do-release-upgrade
../subjects/md5sum.fast  /usr/bin/dpkg
../subjects/md5sum.fast  /usr/bin/dpkg-architecture
../subjects/md5sum.fast  /usr/bin/dpkg-buildflags
../subjects/md5sum.fast  /usr/bin/dpkg-buildpackage
../subjects/md5sum.fast  /usr/bin/dpkg-checkbuilddeps
../subjects/md5sum.fast  /usr/bin/dpkg-deb
../subjects/md5sum.fast  /usr/bin/dpkg-distaddfile
../subjects/md5sum.fast  /usr/bin/dpkg-divert
../subjects/md5sum.fast  /usr/bin/dpkg-genchanges
../subjects/md5sum.fast  /usr/bin/dpkg-gencontrol
../subjects/md5sum.fast  /usr/bin/dpkg-gensymbols
../subjects/md5sum.fast  /usr/bin/dpkg-maintscript-helper
../subjects/md5sum.fast  /usr/bin/dpkg-mergechangelogs
../subjects/md5sum.fast  /usr/bin/dpkg-name
../subjects/md5sum.fast  /usr/bin/dpkg-parsechangelog
../subjects/md5sum.fast  /usr/bin/dpkg-query
../subjects/md5sum.fast  /usr/bin/dpkg-scanpackages
../subjects/md5sum.fast  /usr/bin/dpkg-scansources
../subjects/md5sum.fast  /usr/bin/dpkg-shlibdeps
../subjects/md5sum.fast  /usr/bin/dpkg-source
../subjects/md5sum.fast  /usr/bin/dpkg-split
../subjects/md5sum.fast  /usr/bin/dpkg-statoverride
../subjects/md5sum.fast  /usr/bin/dpkg-trigger
../subjects/md5sum.fast  /usr/bin/dpkg-vendor
../subjects/md5sum.fast  /usr/bin/dropdb
../subjects/md5sum.fast  /usr/bin/droplang
../subjects/md5sum.fast  /usr/bin/dropuser
../subjects/md5sum.fast  /usr/bin/dstat
../subjects/md5sum.fast  /usr/bin/dtc
../subjects/md5sum.fast  /usr/bin/dtdiff
../subjects/md5sum.fast  /usr/bin/du
../subjects/md5sum.fast  /usr/bin/dumpkeys
../subjects/md5sum.fast  /usr/bin/dwp
../subjects/md5sum.fast  /usr/bin/easy_install
../subjects/md5sum.fast  /usr/bin/easy_install3
../subjects/md5sum.fast  /usr/bin/ec2metadata
../subjects/md5sum.fast  /usr/bin/edit
../subjects/md5sum.fast  /usr/bin/editdiff
../subjects/md5sum.fast  /usr/bin/editor
../subjects/md5sum.fast  /usr/bin/editres
../subjects/md5sum.fast  /usr/bin/eject
../subjects/md5sum.fast  /usr/bin/elfedit
../subjects/md5sum.fast  /usr/bin/enc2xs
../subjects/md5sum.fast  /usr/bin/encguess
../subjects/md5sum.fast  /usr/bin/enchant
../subjects/md5sum.fast  /usr/bin/enchant-lsmod
../subjects/md5sum.fast  /usr/bin/env
../subjects/md5sum.fast  /usr/bin/envsubst
../subjects/md5sum.fast  /usr/bin/eqn
../subjects/md5sum.fast  /usr/bin/eventlogadm
../subjects/md5sum.fast  /usr/bin/ex
../subjects/md5sum.fast  /usr/bin/expand
../subjects/md5sum.fast  /usr/bin/expiry
../subjects/md5sum.fast  /usr/bin/expr
../subjects/md5sum.fast  /usr/bin/extcheck
../subjects/md5sum.fast  /usr/bin/factor
../subjects/md5sum.fast  /usr/bin/faillog
../subjects/md5sum.fast  /usr/bin/faked-sysv
../subjects/md5sum.fast  /usr/bin/faked-tcp
../subjects/md5sum.fast  /usr/bin/fakeroot
../subjects/md5sum.fast  /usr/bin/fakeroot-sysv
../subjects/md5sum.fast  /usr/bin/fakeroot-tcp
../subjects/md5sum.fast  /usr/bin/fallocate
../subjects/md5sum.fast  /usr/bin/fc-cache
../subjects/md5sum.fast  /usr/bin/fc-cat
../subjects/md5sum.fast  /usr/bin/fc-list
../subjects/md5sum.fast  /usr/bin/fc-match
../subjects/md5sum.fast  /usr/bin/fc-pattern
../subjects/md5sum.fast  /usr/bin/fc-query
../subjects/md5sum.fast  /usr/bin/fc-scan
../subjects/md5sum.fast  /usr/bin/fc-validate
../subjects/md5sum.fast  /usr/bin/fdtdump
../subjects/md5sum.fast  /usr/bin/fdtget
../subjects/md5sum.fast  /usr/bin/fdtput
../subjects/md5sum.fast  /usr/bin/filan
../subjects/md5sum.fast  /usr/bin/file
../subjects/md5sum.fast  /usr/bin/file-rename
../subjects/md5sum.fast  /usr/bin/filterdiff
../subjects/md5sum.fast  /usr/bin/find
../subjects/md5sum.fast  /usr/bin/fixcvsdiff
../subjects/md5sum.fast  /usr/bin/flex
../subjects/md5sum.fast  /usr/bin/flex++
../subjects/md5sum.fast  /usr/bin/flipdiff
../subjects/md5sum.fast  /usr/bin/flock
../subjects/md5sum.fast  /usr/bin/fmt
../subjects/md5sum.fast  /usr/bin/fold
../subjects/md5sum.fast  /usr/bin/fonttosfnt
../subjects/md5sum.fast  /usr/bin/free
../subjects/md5sum.fast  /usr/bin/from
../subjects/md5sum.fast  /usr/bin/ftp
../subjects/md5sum.fast  /usr/bin/funzip
../subjects/md5sum.fast  /usr/bin/g++
../subjects/md5sum.fast  /usr/bin/g++-4.4
../subjects/md5sum.fast  /usr/bin/g++-4.7
../subjects/md5sum.fast  /usr/bin/g++-5
../subjects/md5sum.fast  /usr/bin/gapplication
../subjects/md5sum.fast  /usr/bin/gatttool
../subjects/md5sum.fast  /usr/bin/gawk
../subjects/md5sum.fast  /usr/bin/gcc
../subjects/md5sum.fast  /usr/bin/gcc-4.4
../subjects/md5sum.fast  /usr/bin/gcc-4.7
../subjects/md5sum.fast  /usr/bin/gcc-5
../subjects/md5sum.fast  /usr/bin/gcc-ar
../subjects/md5sum.fast  /usr/bin/gcc-ar-4.7
../subjects/md5sum.fast  /usr/bin/gcc-ar-5
../subjects/md5sum.fast  /usr/bin/gcc-nm
../subjects/md5sum.fast  /usr/bin/gcc-nm-4.7
../subjects/md5sum.fast  /usr/bin/gcc-nm-5
../subjects/md5sum.fast  /usr/bin/gcc-ranlib
../subjects/md5sum.fast  /usr/bin/gcc-ranlib-4.7
../subjects/md5sum.fast  /usr/bin/gcc-ranlib-5
../subjects/md5sum.fast  /usr/bin/gconf-merge-tree
../subjects/md5sum.fast  /usr/bin/gconftool
../subjects/md5sum.fast  /usr/bin/gconftool-2
../subjects/md5sum.fast  /usr/bin/gcore
../subjects/md5sum.fast  /usr/bin/gcov
../subjects/md5sum.fast  /usr/bin/gcov-4.4
../subjects/md5sum.fast  /usr/bin/gcov-4.7
../subjects/md5sum.fast  /usr/bin/gcov-5
../subjects/md5sum.fast  /usr/bin/gcov-tool
../subjects/md5sum.fast  /usr/bin/gcov-tool-5
../subjects/md5sum.fast  /usr/bin/gcr-viewer
../subjects/md5sum.fast  /usr/bin/gdb
../subjects/md5sum.fast  /usr/bin/gdb-add-index
../subjects/md5sum.fast  /usr/bin/gdbserver
../subjects/md5sum.fast  /usr/bin/gdbtui
../subjects/md5sum.fast  /usr/bin/gdbus
../subjects/md5sum.fast  /usr/bin/gencat
../subjects/md5sum.fast  /usr/bin/gendiff
../subjects/md5sum.fast  /usr/bin/genisoimage
../subjects/md5sum.fast  /usr/bin/gen-preseed
../subjects/md5sum.fast  /usr/bin/geqn
../subjects/md5sum.fast  /usr/bin/GET
../subjects/md5sum.fast  /usr/bin/getcifsacl
../subjects/md5sum.fast  /usr/bin/getconf
../subjects/md5sum.fast  /usr/bin/geteltorito
../subjects/md5sum.fast  /usr/bin/getent
../subjects/md5sum.fast  /usr/bin/getfacl
../subjects/md5sum.fast  /usr/bin/getfattr
../subjects/md5sum.fast  /usr/bin/getkeycodes
../subjects/md5sum.fast  /usr/bin/getopt
../subjects/md5sum.fast  /usr/bin/gettext
../subjects/md5sum.fast  /usr/bin/gettextize
../subjects/md5sum.fast  /usr/bin/gettext.sh
../subjects/md5sum.fast  /usr/bin/ginstall-info
../subjects/md5sum.fast  /usr/bin/gio-querymodules
../subjects/md5sum.fast  /usr/bin/git
../subjects/md5sum.fast  /usr/bin/git-receive-pack
../subjects/md5sum.fast  /usr/bin/git-shell
../subjects/md5sum.fast  /usr/bin/git-upload-archive
../subjects/md5sum.fast  /usr/bin/git-upload-pack
../subjects/md5sum.fast  /usr/bin/gkbd-keyboard-display
../subjects/md5sum.fast  /usr/bin/g++-libc++
../subjects/md5sum.fast  /usr/bin/glib-compile-resources
../subjects/md5sum.fast  /usr/bin/glib-compile-schemas
../subjects/md5sum.fast  /usr/bin/gnome-file-share-properties
../subjects/md5sum.fast  /usr/bin/gnome-help
../subjects/md5sum.fast  /usr/bin/gnome-keyring
../subjects/md5sum.fast  /usr/bin/gnome-keyring-3
../subjects/md5sum.fast  /usr/bin/gnome-keyring-daemon
../subjects/md5sum.fast  /usr/bin/gnome-power-statistics
../subjects/md5sum.fast  /usr/bin/gnome-screensaver
../subjects/md5sum.fast  /usr/bin/gnome-screensaver-command
../subjects/md5sum.fast  /usr/bin/gnome-session
../subjects/md5sum.fast  /usr/bin/gnome-session-inhibit
../subjects/md5sum.fast  /usr/bin/gnome-session-properties
../subjects/md5sum.fast  /usr/bin/gnome-session-quit
../subjects/md5sum.fast  /usr/bin/gold
../subjects/md5sum.fast  /usr/bin/gpasswd
../subjects/md5sum.fast  /usr/bin/gperf
../subjects/md5sum.fast  /usr/bin/gpg
../subjects/md5sum.fast  /usr/bin/gpg-agent
../subjects/md5sum.fast  /usr/bin/gpg-connect-agent
../subjects/md5sum.fast  /usr/bin/gpgsplit
../subjects/md5sum.fast  /usr/bin/gpgv
../subjects/md5sum.fast  /usr/bin/gpg-zip
../subjects/md5sum.fast  /usr/bin/gpic
../subjects/md5sum.fast  /usr/bin/gprof
../subjects/md5sum.fast  /usr/bin/grepdiff
../subjects/md5sum.fast  /usr/bin/gresource
../subjects/md5sum.fast  /usr/bin/groff
../subjects/md5sum.fast  /usr/bin/grog
../subjects/md5sum.fast  /usr/bin/grops
../subjects/md5sum.fast  /usr/bin/grotty
../subjects/md5sum.fast  /usr/bin/groups
../subjects/md5sum.fast  /usr/bin/growpart
../subjects/md5sum.fast  /usr/bin/grub-editenv
../subjects/md5sum.fast  /usr/bin/grub-file
../subjects/md5sum.fast  /usr/bin/grub-fstest
../subjects/md5sum.fast  /usr/bin/grub-glue-efi
../subjects/md5sum.fast  /usr/bin/grub-kbdcomp
../subjects/md5sum.fast  /usr/bin/grub-menulst2cfg
../subjects/md5sum.fast  /usr/bin/grub-mkfont
../subjects/md5sum.fast  /usr/bin/grub-mkimage
../subjects/md5sum.fast  /usr/bin/grub-mklayout
../subjects/md5sum.fast  /usr/bin/grub-mknetdir
../subjects/md5sum.fast  /usr/bin/grub-mkpasswd-pbkdf2
../subjects/md5sum.fast  /usr/bin/grub-mkrelpath
../subjects/md5sum.fast  /usr/bin/grub-mkrescue
../subjects/md5sum.fast  /usr/bin/grub-mkstandalone
../subjects/md5sum.fast  /usr/bin/grub-mount
../subjects/md5sum.fast  /usr/bin/grub-render-label
../subjects/md5sum.fast  /usr/bin/grub-script-check
../subjects/md5sum.fast  /usr/bin/grub-syslinux2cfg
../subjects/md5sum.fast  /usr/bin/gsettings
../subjects/md5sum.fast  /usr/bin/gsettings-data-convert
../subjects/md5sum.fast  /usr/bin/gsettings-schema-convert
../subjects/md5sum.fast  /usr/bin/gtbl
../subjects/md5sum.fast  /usr/bin/gtf
../subjects/md5sum.fast  /usr/bin/gtk-builder-tool
../subjects/md5sum.fast  /usr/bin/gtk-launch
../subjects/md5sum.fast  /usr/bin/gtk-update-icon-cache
../subjects/md5sum.fast  /usr/bin/gtk-update-icon-cache-3.0
../subjects/md5sum.fast  /usr/bin/h2ph
../subjects/md5sum.fast  /usr/bin/h2xs
../subjects/md5sum.fast  /usr/bin/hardening-check
../subjects/md5sum.fast  /usr/bin/hciattach
../subjects/md5sum.fast  /usr/bin/hcitool
../subjects/md5sum.fast  /usr/bin/hd
../subjects/md5sum.fast  /usr/bin/head
../subjects/md5sum.fast  /usr/bin/HEAD
../subjects/md5sum.fast  /usr/bin/helpztags
../subjects/md5sum.fast  /usr/bin/hex2hcd
../subjects/md5sum.fast  /usr/bin/hexdump
../subjects/md5sum.fast  /usr/bin/host
../subjects/md5sum.fast  /usr/bin/hostid
../subjects/md5sum.fast  /usr/bin/hostnamectl
../subjects/md5sum.fast  /usr/bin/i386
../subjects/md5sum.fast  /usr/bin/i686-linux-gnu-pkg-config
../subjects/md5sum.fast  /usr/bin/iasl
../subjects/md5sum.fast  /usr/bin/ibus
../subjects/md5sum.fast  /usr/bin/ibus-daemon
../subjects/md5sum.fast  /usr/bin/ibus-setup
../subjects/md5sum.fast  /usr/bin/iconv
../subjects/md5sum.fast  /usr/bin/id
../subjects/md5sum.fast  /usr/bin/idlj
../subjects/md5sum.fast  /usr/bin/ifnames
../subjects/md5sum.fast  /usr/bin/igawk
../subjects/md5sum.fast  /usr/bin/im-config
../subjects/md5sum.fast  /usr/bin/im-launch
../subjects/md5sum.fast  /usr/bin/info
../subjects/md5sum.fast  /usr/bin/infobrowser
../subjects/md5sum.fast  /usr/bin/infocmp
../subjects/md5sum.fast  /usr/bin/infotocap
../subjects/md5sum.fast  /usr/bin/init-checkconf
../subjects/md5sum.fast  /usr/bin/initctl2dot
../subjects/md5sum.fast  /usr/bin/inotifywait
../subjects/md5sum.fast  /usr/bin/inotifywatch
../subjects/md5sum.fast  /usr/bin/install
../subjects/md5sum.fast  /usr/bin/install-info
../subjects/md5sum.fast  /usr/bin/install-printerdriver
../subjects/md5sum.fast  /usr/bin/instmodsh
../subjects/md5sum.fast  /usr/bin/interdiff
../subjects/md5sum.fast  /usr/bin/ionice
../subjects/md5sum.fast  /usr/bin/iostat
../subjects/md5sum.fast  /usr/bin/ipcmk
../subjects/md5sum.fast  /usr/bin/ipcrm
../subjects/md5sum.fast  /usr/bin/ipcs
../subjects/md5sum.fast  /usr/bin/iptables-xml
../subjects/md5sum.fast  /usr/bin/ischroot
../subjects/md5sum.fast  /usr/bin/iscsiadm
../subjects/md5sum.fast  /usr/bin/isdv4-serial-debugger
../subjects/md5sum.fast  /usr/bin/isdv4-serial-inputattach
../subjects/md5sum.fast  /usr/bin/isodump
../subjects/md5sum.fast  /usr/bin/isoinfo
../subjects/md5sum.fast  /usr/bin/isovfy
../subjects/md5sum.fast  /usr/bin/ispell-wrapper
../subjects/md5sum.fast  /usr/bin/jar
../subjects/md5sum.fast  /usr/bin/jarsigner
../subjects/md5sum.fast  /usr/bin/java
../subjects/md5sum.fast  /usr/bin/javac
../subjects/md5sum.fast  /usr/bin/javadoc
../subjects/md5sum.fast  /usr/bin/javah
../subjects/md5sum.fast  /usr/bin/javap
../subjects/md5sum.fast  /usr/bin/jcmd
../subjects/md5sum.fast  /usr/bin/jconsole
../subjects/md5sum.fast  /usr/bin/jdb
../subjects/md5sum.fast  /usr/bin/jexec
../subjects/md5sum.fast  /usr/bin/jhat
../subjects/md5sum.fast  /usr/bin/jinfo
../subjects/md5sum.fast  /usr/bin/jmap
../subjects/md5sum.fast  /usr/bin/join
../subjects/md5sum.fast  /usr/bin/jps
../subjects/md5sum.fast  /usr/bin/jq
../subjects/md5sum.fast  /usr/bin/jrunscript
../subjects/md5sum.fast  /usr/bin/jsadebugd
../subjects/md5sum.fast  /usr/bin/json_pp
../subjects/md5sum.fast  /usr/bin/jstack
../subjects/md5sum.fast  /usr/bin/jstat
../subjects/md5sum.fast  /usr/bin/jstatd
../subjects/md5sum.fast  /usr/bin/kbdinfo
../subjects/md5sum.fast  /usr/bin/kcbench
../subjects/md5sum.fast  /usr/bin/keep-one-running
../subjects/md5sum.fast  /usr/bin/keytool
../subjects/md5sum.fast  /usr/bin/killall
../subjects/md5sum.fast  /usr/bin/kmodsign
../subjects/md5sum.fast  /usr/bin/l2ping
../subjects/md5sum.fast  /usr/bin/l2test
../subjects/md5sum.fast  /usr/bin/last
../subjects/md5sum.fast  /usr/bin/lastb
../subjects/md5sum.fast  /usr/bin/lastlog
../subjects/md5sum.fast  /usr/bin/lcf
../subjects/md5sum.fast  /usr/bin/ld
../subjects/md5sum.fast  /usr/bin/ld.bfd
../subjects/md5sum.fast  /usr/bin/ldd
../subjects/md5sum.fast  /usr/bin/ld.gold
../subjects/md5sum.fast  /usr/bin/less
../subjects/md5sum.fast  /usr/bin/lessecho
../subjects/md5sum.fast  /usr/bin/lessfile
../subjects/md5sum.fast  /usr/bin/lesskey
../subjects/md5sum.fast  /usr/bin/lesspipe
../subjects/md5sum.fast  /usr/bin/lex
../subjects/md5sum.fast  /usr/bin/lexgrog
../subjects/md5sum.fast  /usr/bin/libnetcfg
../subjects/md5sum.fast  /usr/bin/librados-config
../subjects/md5sum.fast  /usr/bin/libtool
../subjects/md5sum.fast  /usr/bin/libtoolize
../subjects/md5sum.fast  /usr/bin/libwacom-list-local-devices
../subjects/md5sum.fast  /usr/bin/line
../subjects/md5sum.fast  /usr/bin/link
../subjects/md5sum.fast  /usr/bin/lintian
../subjects/md5sum.fast  /usr/bin/lintian-info
../subjects/md5sum.fast  /usr/bin/lintian-lab-tool
../subjects/md5sum.fast  /usr/bin/linux32
../subjects/md5sum.fast  /usr/bin/linux64
../subjects/md5sum.fast  /usr/bin/linux-boot-prober
../subjects/md5sum.fast  /usr/bin/linux-check-removal
../subjects/md5sum.fast  /usr/bin/linux-update-symlinks
../subjects/md5sum.fast  /usr/bin/linux-version
../subjects/md5sum.fast  /usr/bin/listres
../subjects/md5sum.fast  /usr/bin/llc-3.3
../subjects/md5sum.fast  /usr/bin/lli-3.3
../subjects/md5sum.fast  /usr/bin/llvm-ar-3.3
../subjects/md5sum.fast  /usr/bin/llvm-as-3.3
../subjects/md5sum.fast  /usr/bin/llvm-bcanalyzer-3.3
../subjects/md5sum.fast  /usr/bin/llvm-config-3.3
../subjects/md5sum.fast  /usr/bin/llvm-cov-3.3
../subjects/md5sum.fast  /usr/bin/llvm-diff-3.3
../subjects/md5sum.fast  /usr/bin/llvm-dis-3.3
../subjects/md5sum.fast  /usr/bin/llvm-dwarfdump-3.3
../subjects/md5sum.fast  /usr/bin/llvm-extract-3.3
../subjects/md5sum.fast  /usr/bin/llvm-link-3.3
../subjects/md5sum.fast  /usr/bin/llvm-mc-3.3
../subjects/md5sum.fast  /usr/bin/llvm-mcmarkup-3.3
../subjects/md5sum.fast  /usr/bin/llvm-nm-3.3
../subjects/md5sum.fast  /usr/bin/llvm-objdump-3.3
../subjects/md5sum.fast  /usr/bin/llvm-prof-3.3
../subjects/md5sum.fast  /usr/bin/llvm-ranlib-3.3
../subjects/md5sum.fast  /usr/bin/llvm-readobj-3.3
../subjects/md5sum.fast  /usr/bin/llvm-rtdyld-3.3
../subjects/md5sum.fast  /usr/bin/llvm-size-3.3
../subjects/md5sum.fast  /usr/bin/llvm-stress-3.3
../subjects/md5sum.fast  /usr/bin/llvm-symbolizer-3.3
../subjects/md5sum.fast  /usr/bin/llvm-tblgen-3.3
../subjects/md5sum.fast  /usr/bin/lnstat
../subjects/md5sum.fast  /usr/bin/loadkeys
../subjects/md5sum.fast  /usr/bin/loadunimap
../subjects/md5sum.fast  /usr/bin/locale
../subjects/md5sum.fast  /usr/bin/localectl
../subjects/md5sum.fast  /usr/bin/localedef
../subjects/md5sum.fast  /usr/bin/locate
../subjects/md5sum.fast  /usr/bin/logger
../subjects/md5sum.fast  /usr/bin/logname
../subjects/md5sum.fast  /usr/bin/look
../subjects/md5sum.fast  /usr/bin/lorder
../subjects/md5sum.fast  /usr/bin/lsattr
../subjects/md5sum.fast  /usr/bin/lsb_release
../subjects/md5sum.fast  /usr/bin/lscpu
../subjects/md5sum.fast  /usr/bin/lsdiff
../subjects/md5sum.fast  /usr/bin/lshw
../subjects/md5sum.fast  /usr/bin/lsinitramfs
../subjects/md5sum.fast  /usr/bin/lsipc
../subjects/md5sum.fast  /usr/bin/lslocks
../subjects/md5sum.fast  /usr/bin/lslogins
../subjects/md5sum.fast  /usr/bin/lsof
../subjects/md5sum.fast  /usr/bin/lspci
../subjects/md5sum.fast  /usr/bin/lspgpot
../subjects/md5sum.fast  /usr/bin/lsusb
../subjects/md5sum.fast  /usr/bin/ltrace
../subjects/md5sum.fast  /usr/bin/luit
../subjects/md5sum.fast  /usr/bin/lwp-download
../subjects/md5sum.fast  /usr/bin/lwp-dump
../subjects/md5sum.fast  /usr/bin/lwp-mirror
../subjects/md5sum.fast  /usr/bin/lwp-request
../subjects/md5sum.fast  /usr/bin/lxc
../subjects/md5sum.fast  /usr/bin/lxcfs
../subjects/md5sum.fast  /usr/bin/lxd
../subjects/md5sum.fast  /usr/bin/lzcat
../subjects/md5sum.fast  /usr/bin/lzcmp
../subjects/md5sum.fast  /usr/bin/lzdiff
../subjects/md5sum.fast  /usr/bin/lzegrep
../subjects/md5sum.fast  /usr/bin/lzfgrep
../subjects/md5sum.fast  /usr/bin/lzgrep
../subjects/md5sum.fast  /usr/bin/lzless
../subjects/md5sum.fast  /usr/bin/lzma
../subjects/md5sum.fast  /usr/bin/lzmainfo
../subjects/md5sum.fast  /usr/bin/lzmore
../subjects/md5sum.fast  /usr/bin/m4
../subjects/md5sum.fast  /usr/bin/macho-dump-3.3
../subjects/md5sum.fast  /usr/bin/make
../subjects/md5sum.fast  /usr/bin/make-first-existing-target
../subjects/md5sum.fast  /usr/bin/makeinfo
../subjects/md5sum.fast  /usr/bin/man
../subjects/md5sum.fast  /usr/bin/mandb
../subjects/md5sum.fast  /usr/bin/manifest
../subjects/md5sum.fast  /usr/bin/manpath
../subjects/md5sum.fast  /usr/bin/mapscrn
../subjects/md5sum.fast  /usr/bin/mawk
../subjects/md5sum.fast  /usr/bin/mcookie
../subjects/md5sum.fast  /usr/bin/md5sum
../subjects/md5sum.fast  /usr/bin/md5sum.textutils
../subjects/md5sum.fast  /usr/bin/mesg
../subjects/md5sum.fast  /usr/bin/mkfifo
../subjects/md5sum.fast  /usr/bin/mkfontdir
../subjects/md5sum.fast  /usr/bin/mkfontscale
../subjects/md5sum.fast  /usr/bin/mkisofs
../subjects/md5sum.fast  /usr/bin/mk_modmap
../subjects/md5sum.fast  /usr/bin/mksquashfs
../subjects/md5sum.fast  /usr/bin/mkzftree
../subjects/md5sum.fast  /usr/bin/mlocate
../subjects/md5sum.fast  /usr/bin/mmcli
../subjects/md5sum.fast  /usr/bin/mokutil
../subjects/md5sum.fast  /usr/bin/mousetweaks
../subjects/md5sum.fast  /usr/bin/mpstat
../subjects/md5sum.fast  /usr/bin/msgattrib
../subjects/md5sum.fast  /usr/bin/msgcat
../subjects/md5sum.fast  /usr/bin/msgcmp
../subjects/md5sum.fast  /usr/bin/msgcomm
../subjects/md5sum.fast  /usr/bin/msgconv
../subjects/md5sum.fast  /usr/bin/msgen
../subjects/md5sum.fast  /usr/bin/msgexec
../subjects/md5sum.fast  /usr/bin/msgfilter
../subjects/md5sum.fast  /usr/bin/msgfmt
../subjects/md5sum.fast  /usr/bin/msggrep
../subjects/md5sum.fast  /usr/bin/msginit
../subjects/md5sum.fast  /usr/bin/msgmerge
../subjects/md5sum.fast  /usr/bin/msgunfmt
../subjects/md5sum.fast  /usr/bin/msguniq
../subjects/md5sum.fast  /usr/bin/mtr
../subjects/md5sum.fast  /usr/bin/mtrace
../subjects/md5sum.fast  /usr/bin/namei
../subjects/md5sum.fast  /usr/bin/native2ascii
../subjects/md5sum.fast  /usr/bin/nawk
../subjects/md5sum.fast  /usr/bin/ncal
../subjects/md5sum.fast  /usr/bin/neqn
../subjects/md5sum.fast  /usr/bin/net
../subjects/md5sum.fast  /usr/bin/netkit-ftp
../subjects/md5sum.fast  /usr/bin/newgidmap
../subjects/md5sum.fast  /usr/bin/newgrp
../subjects/md5sum.fast  /usr/bin/newuidmap
../subjects/md5sum.fast  /usr/bin/NF
../subjects/md5sum.fast  /usr/bin/ngettext
../subjects/md5sum.fast  /usr/bin/nice
../subjects/md5sum.fast  /usr/bin/ninja
../subjects/md5sum.fast  /usr/bin/nl
../subjects/md5sum.fast  /usr/bin/nm
../subjects/md5sum.fast  /usr/bin/nm-applet
../subjects/md5sum.fast  /usr/bin/nmblookup
../subjects/md5sum.fast  /usr/bin/nmcli
../subjects/md5sum.fast  /usr/bin/nm-connection-editor
../subjects/md5sum.fast  /usr/bin/nm-online
../subjects/md5sum.fast  /usr/bin/nmtui
../subjects/md5sum.fast  /usr/bin/nmtui-connect
../subjects/md5sum.fast  /usr/bin/nmtui-edit
../subjects/md5sum.fast  /usr/bin/nmtui-hostname
../subjects/md5sum.fast  /usr/bin/nohup
../subjects/md5sum.fast  /usr/bin/nproc
../subjects/md5sum.fast  /usr/bin/nroff
../subjects/md5sum.fast  /usr/bin/nsenter
../subjects/md5sum.fast  /usr/bin/nslookup
../subjects/md5sum.fast  /usr/bin/nspr-config
../subjects/md5sum.fast  /usr/bin/nss-config
../subjects/md5sum.fast  /usr/bin/nstat
../subjects/md5sum.fast  /usr/bin/nsupdate
../subjects/md5sum.fast  /usr/bin/ntfsdecrypt
../subjects/md5sum.fast  /usr/bin/ntlm_auth
../subjects/md5sum.fast  /usr/bin/numfmt
../subjects/md5sum.fast  /usr/bin/nvidia-modprobe
../subjects/md5sum.fast  /usr/bin/nvidia-settings
../subjects/md5sum.fast  /usr/bin/obexctl
../subjects/md5sum.fast  /usr/bin/objcopy
../subjects/md5sum.fast  /usr/bin/objdump
../subjects/md5sum.fast  /usr/bin/od
../subjects/md5sum.fast  /usr/bin/odb
../subjects/md5sum.fast  /usr/bin/oLschema2ldif
../subjects/md5sum.fast  /usr/bin/on_ac_power
../subjects/md5sum.fast  /usr/bin/online-accounts-preferences
../subjects/md5sum.fast  /usr/bin/openssl
../subjects/md5sum.fast  /usr/bin/opt-3.3
../subjects/md5sum.fast  /usr/bin/orbd
../subjects/md5sum.fast  /usr/bin/os-prober
../subjects/md5sum.fast  /usr/bin/p11-kit
../subjects/md5sum.fast  /usr/bin/pacat
../subjects/md5sum.fast  /usr/bin/pack200
../subjects/md5sum.fast  /usr/bin/pacmd
../subjects/md5sum.fast  /usr/bin/pactl
../subjects/md5sum.fast  /usr/bin/padsp
../subjects/md5sum.fast  /usr/bin/pager
../subjects/md5sum.fast  /usr/bin/pamon
../subjects/md5sum.fast  /usr/bin/paplay
../subjects/md5sum.fast  /usr/bin/parec
../subjects/md5sum.fast  /usr/bin/parecord
../subjects/md5sum.fast  /usr/bin/parsechangelog
../subjects/md5sum.fast  /usr/bin/partx
../subjects/md5sum.fast  /usr/bin/passwd
../subjects/md5sum.fast  /usr/bin/paste
../subjects/md5sum.fast  /usr/bin/pastebinit
../subjects/md5sum.fast  /usr/bin/pasuspender
../subjects/md5sum.fast  /usr/bin/patch
../subjects/md5sum.fast  /usr/bin/pathchk
../subjects/md5sum.fast  /usr/bin/pax11publish
../subjects/md5sum.fast  /usr/bin/pbget
../subjects/md5sum.fast  /usr/bin/pbput
../subjects/md5sum.fast  /usr/bin/pbputs
../subjects/md5sum.fast  /usr/bin/pcimodules
../subjects/md5sum.fast  /usr/bin/pdb
../subjects/md5sum.fast  /usr/bin/pdb2.7
../subjects/md5sum.fast  /usr/bin/pdb3
../subjects/md5sum.fast  /usr/bin/pdb3.5
../subjects/md5sum.fast  /usr/bin/pdbedit
../subjects/md5sum.fast  /usr/bin/pdftexi2dvi
../subjects/md5sum.fast  /usr/bin/peekfd
../subjects/md5sum.fast  /usr/bin/perf
../subjects/md5sum.fast  /usr/bin/perl
../subjects/md5sum.fast  /usr/bin/perl5.22.1
../subjects/md5sum.fast  /usr/bin/perl5.22-x86_64-linux-gnu
../subjects/md5sum.fast  /usr/bin/perlbug
../subjects/md5sum.fast  /usr/bin/perldoc
../subjects/md5sum.fast  /usr/bin/perlivp
../subjects/md5sum.fast  /usr/bin/perlthanks
../subjects/md5sum.fast  /usr/bin/pftp
../subjects/md5sum.fast  /usr/bin/pg
../subjects/md5sum.fast  /usr/bin/pg_archivecleanup
../subjects/md5sum.fast  /usr/bin/pg_basebackup
../subjects/md5sum.fast  /usr/bin/pgbench
../subjects/md5sum.fast  /usr/bin/pg_config
../subjects/md5sum.fast  /usr/bin/pg_conftool
../subjects/md5sum.fast  /usr/bin/pg_createcluster
../subjects/md5sum.fast  /usr/bin/pg_ctlcluster
../subjects/md5sum.fast  /usr/bin/pg_dropcluster
../subjects/md5sum.fast  /usr/bin/pg_dump
../subjects/md5sum.fast  /usr/bin/pg_dumpall
../subjects/md5sum.fast  /usr/bin/pg_isready
../subjects/md5sum.fast  /usr/bin/pg_lsclusters
../subjects/md5sum.fast  /usr/bin/pg_receivexlog
../subjects/md5sum.fast  /usr/bin/pg_recvlogical
../subjects/md5sum.fast  /usr/bin/pg_renamecluster
../subjects/md5sum.fast  /usr/bin/pgrep
../subjects/md5sum.fast  /usr/bin/pg_restore
../subjects/md5sum.fast  /usr/bin/pg_upgradecluster
../subjects/md5sum.fast  /usr/bin/pg_virtualenv
../subjects/md5sum.fast  /usr/bin/pic
../subjects/md5sum.fast  /usr/bin/pico
../subjects/md5sum.fast  /usr/bin/piconv
../subjects/md5sum.fast  /usr/bin/pidstat
../subjects/md5sum.fast  /usr/bin/pigz
../subjects/md5sum.fast  /usr/bin/pinentry
../subjects/md5sum.fast  /usr/bin/pinentry-curses
../subjects/md5sum.fast  /usr/bin/pinentry-gnome3
../subjects/md5sum.fast  /usr/bin/pinentry-x11
../subjects/md5sum.fast  /usr/bin/pinky
../subjects/md5sum.fast  /usr/bin/pip
../subjects/md5sum.fast  /usr/bin/pip2
../subjects/md5sum.fast  /usr/bin/pip3
../subjects/md5sum.fast  /usr/bin/pkaction
../subjects/md5sum.fast  /usr/bin/pkcheck
../subjects/md5sum.fast  /usr/bin/pkexec
../subjects/md5sum.fast  /usr/bin/pkg-config
../subjects/md5sum.fast  /usr/bin/pkill
../subjects/md5sum.fast  /usr/bin/pkttyagent
../subjects/md5sum.fast  /usr/bin/pl2pm
../subjects/md5sum.fast  /usr/bin/pldd
../subjects/md5sum.fast  /usr/bin/plog
../subjects/md5sum.fast  /usr/bin/pmap
../subjects/md5sum.fast  /usr/bin/po2debconf
../subjects/md5sum.fast  /usr/bin/pod2html
../subjects/md5sum.fast  /usr/bin/pod2man
../subjects/md5sum.fast  /usr/bin/pod2texi
../subjects/md5sum.fast  /usr/bin/pod2text
../subjects/md5sum.fast  /usr/bin/pod2usage
../subjects/md5sum.fast  /usr/bin/podchecker
../subjects/md5sum.fast  /usr/bin/podebconf-display-po
../subjects/md5sum.fast  /usr/bin/podebconf-report-po
../subjects/md5sum.fast  /usr/bin/podselect
../subjects/md5sum.fast  /usr/bin/poff
../subjects/md5sum.fast  /usr/bin/policytool
../subjects/md5sum.fast  /usr/bin/pollinate
../subjects/md5sum.fast  /usr/bin/pon
../subjects/md5sum.fast  /usr/bin/POST
../subjects/md5sum.fast  /usr/bin/pr
../subjects/md5sum.fast  /usr/bin/precat
../subjects/md5sum.fast  /usr/bin/preconv
../subjects/md5sum.fast  /usr/bin/prename
../subjects/md5sum.fast  /usr/bin/preunzip
../subjects/md5sum.fast  /usr/bin/prezip
../subjects/md5sum.fast  /usr/bin/prezip-bin
../subjects/md5sum.fast  /usr/bin/print
../subjects/md5sum.fast  /usr/bin/printenv
../subjects/md5sum.fast  /usr/bin/printerbanner
../subjects/md5sum.fast  /usr/bin/printf
../subjects/md5sum.fast  /usr/bin/prlimit
../subjects/md5sum.fast  /usr/bin/procan
../subjects/md5sum.fast  /usr/bin/profiles
../subjects/md5sum.fast  /usr/bin/protoc
../subjects/md5sum.fast  /usr/bin/protoc-c
../subjects/md5sum.fast  /usr/bin/prove
../subjects/md5sum.fast  /usr/bin/prtstat
../subjects/md5sum.fast  /usr/bin/psfaddtable
../subjects/md5sum.fast  /usr/bin/psfgettable
../subjects/md5sum.fast  /usr/bin/psfstriptable
../subjects/md5sum.fast  /usr/bin/psfxtable
../subjects/md5sum.fast  /usr/bin/psql
../subjects/md5sum.fast  /usr/bin/pstree
../subjects/md5sum.fast  /usr/bin/pstree.x11
../subjects/md5sum.fast  /usr/bin/pstruct
../subjects/md5sum.fast  /usr/bin/ptar
../subjects/md5sum.fast  /usr/bin/ptardiff
../subjects/md5sum.fast  /usr/bin/ptargrep
../subjects/md5sum.fast  /usr/bin/ptx
../subjects/md5sum.fast  /usr/bin/pulseaudio
../subjects/md5sum.fast  /usr/bin/purge-old-kernels
../subjects/md5sum.fast  /usr/bin/pwdx
../subjects/md5sum.fast  /usr/bin/py3clean
../subjects/md5sum.fast  /usr/bin/py3compile
../subjects/md5sum.fast  /usr/bin/py3versions
../subjects/md5sum.fast  /usr/bin/pybuild
../subjects/md5sum.fast  /usr/bin/pyclean
../subjects/md5sum.fast  /usr/bin/pycompile
../subjects/md5sum.fast  /usr/bin/pydoc
../subjects/md5sum.fast  /usr/bin/pydoc2.7
../subjects/md5sum.fast  /usr/bin/pydoc3
../subjects/md5sum.fast  /usr/bin/pydoc3.5
../subjects/md5sum.fast  /usr/bin/pygettext
../subjects/md5sum.fast  /usr/bin/pygettext2.7
../subjects/md5sum.fast  /usr/bin/pygettext3
../subjects/md5sum.fast  /usr/bin/pygettext3.5
../subjects/md5sum.fast  /usr/bin/python
../subjects/md5sum.fast  /usr/bin/python2
../subjects/md5sum.fast  /usr/bin/python2.7
../subjects/md5sum.fast  /usr/bin/python3
../subjects/md5sum.fast  /usr/bin/python3.5
../subjects/md5sum.fast  /usr/bin/python3.5-config
../subjects/md5sum.fast  /usr/bin/python3.5m
../subjects/md5sum.fast  /usr/bin/python3.5m-config
../subjects/md5sum.fast  /usr/bin/python3-config
../subjects/md5sum.fast  /usr/bin/python3m
../subjects/md5sum.fast  /usr/bin/python3m-config
../subjects/md5sum.fast  /usr/bin/pyversions
../subjects/md5sum.fast  /usr/bin/ranlib
../subjects/md5sum.fast  /usr/bin/rcp
../subjects/md5sum.fast  /usr/bin/rctest
../subjects/md5sum.fast  /usr/bin/readelf
../subjects/md5sum.fast  /usr/bin/realpath
../subjects/md5sum.fast  /usr/bin/recode-sr-latin
../subjects/md5sum.fast  /usr/bin/recountdiff
../subjects/md5sum.fast  /usr/bin/rediff
../subjects/md5sum.fast  /usr/bin/regexp-assemble
../subjects/md5sum.fast  /usr/bin/reindexdb
../subjects/md5sum.fast  /usr/bin/rename
../subjects/md5sum.fast  /usr/bin/rename.ul
../subjects/md5sum.fast  /usr/bin/renice
../subjects/md5sum.fast  /usr/bin/report-hw
../subjects/md5sum.fast  /usr/bin/reset
../subjects/md5sum.fast  /usr/bin/resizecons
../subjects/md5sum.fast  /usr/bin/resizepart
../subjects/md5sum.fast  /usr/bin/rev
../subjects/md5sum.fast  /usr/bin/rfcomm
../subjects/md5sum.fast  /usr/bin/rgrep
../subjects/md5sum.fast  /usr/bin/rlogin
../subjects/md5sum.fast  /usr/bin/rmic
../subjects/md5sum.fast  /usr/bin/rmid
../subjects/md5sum.fast  /usr/bin/rmiregistry
../subjects/md5sum.fast  /usr/bin/routef
../subjects/md5sum.fast  /usr/bin/routel
../subjects/md5sum.fast  /usr/bin/rpcclient
../subjects/md5sum.fast  /usr/bin/rpcgen
../subjects/md5sum.fast  /usr/bin/rpm
../subjects/md5sum.fast  /usr/bin/rpm2archive
../subjects/md5sum.fast  /usr/bin/rpm2cpio
../subjects/md5sum.fast  /usr/bin/rpmbuild
../subjects/md5sum.fast  /usr/bin/rpmdb
../subjects/md5sum.fast  /usr/bin/rpmgraph
../subjects/md5sum.fast  /usr/bin/rpmkeys
../subjects/md5sum.fast  /usr/bin/rpmquery
../subjects/md5sum.fast  /usr/bin/rpmsign
../subjects/md5sum.fast  /usr/bin/rpmspec
../subjects/md5sum.fast  /usr/bin/rpmverify
../subjects/md5sum.fast  /usr/bin/rsh
../subjects/md5sum.fast  /usr/bin/rsync
../subjects/md5sum.fast  /usr/bin/rtstat
../subjects/md5sum.fast  /usr/bin/runcon
../subjects/md5sum.fast  /usr/bin/run-mailcap
../subjects/md5sum.fast  /usr/bin/run-one
../subjects/md5sum.fast  /usr/bin/run-one-constantly
../subjects/md5sum.fast  /usr/bin/run-one-until-failure
../subjects/md5sum.fast  /usr/bin/run-one-until-success
../subjects/md5sum.fast  /usr/bin/run-this-one
../subjects/md5sum.fast  /usr/bin/run-with-aspell
../subjects/md5sum.fast  /usr/bin/rview
../subjects/md5sum.fast  /usr/bin/rvim
../subjects/md5sum.fast  /usr/bin/sadf
../subjects/md5sum.fast  /usr/bin/samba-regedit
../subjects/md5sum.fast  /usr/bin/samba-tool
../subjects/md5sum.fast  /usr/bin/sar
../subjects/md5sum.fast  /usr/bin/sar.sysstat
../subjects/md5sum.fast  /usr/bin/savelog
../subjects/md5sum.fast  /usr/bin/sbattach
../subjects/md5sum.fast  /usr/bin/sbkeysync
../subjects/md5sum.fast  /usr/bin/sbsiglist
../subjects/md5sum.fast  /usr/bin/sbsign
../subjects/md5sum.fast  /usr/bin/sbvarsign
../subjects/md5sum.fast  /usr/bin/sbverify
../subjects/md5sum.fast  /usr/bin/schemagen
../subjects/md5sum.fast  /usr/bin/scp
../subjects/md5sum.fast  /usr/bin/scp-dbus-service
../subjects/md5sum.fast  /usr/bin/screen
../subjects/md5sum.fast  /usr/bin/screendump
../subjects/md5sum.fast  /usr/bin/script
../subjects/md5sum.fast  /usr/bin/scriptreplay
../subjects/md5sum.fast  /usr/bin/sdiff
../subjects/md5sum.fast  /usr/bin/sdptool
../subjects/md5sum.fast  /usr/bin/see
../subjects/md5sum.fast  /usr/bin/select-default-iwrap
../subjects/md5sum.fast  /usr/bin/select-editor
../subjects/md5sum.fast  /usr/bin/sensible-browser
../subjects/md5sum.fast  /usr/bin/sensible-editor
../subjects/md5sum.fast  /usr/bin/sensible-pager
../subjects/md5sum.fast  /usr/bin/seq
../subjects/md5sum.fast  /usr/bin/serialver
../subjects/md5sum.fast  /usr/bin/servertool
../subjects/md5sum.fast  /usr/bin/session-migration
../subjects/md5sum.fast  /usr/bin/setarch
../subjects/md5sum.fast  /usr/bin/setcifsacl
../subjects/md5sum.fast  /usr/bin/setfacl
../subjects/md5sum.fast  /usr/bin/setfattr
../subjects/md5sum.fast  /usr/bin/setkeycodes
../subjects/md5sum.fast  /usr/bin/setleds
../subjects/md5sum.fast  /usr/bin/setlogcons
../subjects/md5sum.fast  /usr/bin/setmetamode
../subjects/md5sum.fast  /usr/bin/setpci
../subjects/md5sum.fast  /usr/bin/setsid
../subjects/md5sum.fast  /usr/bin/setterm
../subjects/md5sum.fast  /usr/bin/setxkbmap
../subjects/md5sum.fast  /usr/bin/sftp
../subjects/md5sum.fast  /usr/bin/sg
../subjects/md5sum.fast  /usr/bin/sha1sum
../subjects/md5sum.fast  /usr/bin/sha224sum
../subjects/md5sum.fast  /usr/bin/sha256sum
../subjects/md5sum.fast  /usr/bin/sha384sum
../subjects/md5sum.fast  /usr/bin/sha512sum
../subjects/md5sum.fast  /usr/bin/sharesec
../subjects/md5sum.fast  /usr/bin/shasum
../subjects/md5sum.fast  /usr/bin/showconsolefont
../subjects/md5sum.fast  /usr/bin/showkey
../subjects/md5sum.fast  /usr/bin/shred
../subjects/md5sum.fast  /usr/bin/shuf
../subjects/md5sum.fast  /usr/bin/signond
../subjects/md5sum.fast  /usr/bin/signonpluginprocess
../subjects/md5sum.fast  /usr/bin/signon-ui
../subjects/md5sum.fast  /usr/bin/size
../subjects/md5sum.fast  /usr/bin/skill
../subjects/md5sum.fast  /usr/bin/slabtop
../subjects/md5sum.fast  /usr/bin/slogin
../subjects/md5sum.fast  /usr/bin/smbcacls
../subjects/md5sum.fast  /usr/bin/smbclient
../subjects/md5sum.fast  /usr/bin/smbcontrol
../subjects/md5sum.fast  /usr/bin/smbcquotas
../subjects/md5sum.fast  /usr/bin/smbget
../subjects/md5sum.fast  /usr/bin/smbpasswd
../subjects/md5sum.fast  /usr/bin/smbspool
../subjects/md5sum.fast  /usr/bin/smbspool_krb5_wrapper
../subjects/md5sum.fast  /usr/bin/smbstatus
../subjects/md5sum.fast  /usr/bin/smbtar
../subjects/md5sum.fast  /usr/bin/smbta-util
../subjects/md5sum.fast  /usr/bin/smbtree
../subjects/md5sum.fast  /usr/bin/snap
../subjects/md5sum.fast  /usr/bin/snapctl
../subjects/md5sum.fast  /usr/bin/snapfuse
../subjects/md5sum.fast  /usr/bin/snice
../subjects/md5sum.fast  /usr/bin/socat
../subjects/md5sum.fast  /usr/bin/soelim
../subjects/md5sum.fast  /usr/bin/sort
../subjects/md5sum.fast  /usr/bin/sosreport
../subjects/md5sum.fast  /usr/bin/sotruss
../subjects/md5sum.fast  /usr/bin/spellintian
../subjects/md5sum.fast  /usr/bin/splain
../subjects/md5sum.fast  /usr/bin/split
../subjects/md5sum.fast  /usr/bin/splitdiff
../subjects/md5sum.fast  /usr/bin/splitfont
../subjects/md5sum.fast  /usr/bin/sprof
../subjects/md5sum.fast  /usr/bin/ssh
../subjects/md5sum.fast  /usr/bin/ssh-add
../subjects/md5sum.fast  /usr/bin/ssh-agent
../subjects/md5sum.fast  /usr/bin/ssh-argv0
../subjects/md5sum.fast  /usr/bin/ssh-copy-id
../subjects/md5sum.fast  /usr/bin/ssh-import-id
../subjects/md5sum.fast  /usr/bin/ssh-import-id-gh
../subjects/md5sum.fast  /usr/bin/ssh-import-id-lp
../subjects/md5sum.fast  /usr/bin/ssh-keygen
../subjects/md5sum.fast  /usr/bin/ssh-keyscan
../subjects/md5sum.fast  /usr/bin/start-pulseaudio-x11
../subjects/md5sum.fast  /usr/bin/stat
../subjects/md5sum.fast  /usr/bin/stdbuf
../subjects/md5sum.fast  /usr/bin/strace
../subjects/md5sum.fast  /usr/bin/strings
../subjects/md5sum.fast  /usr/bin/strip
../subjects/md5sum.fast  /usr/bin/sudo
../subjects/md5sum.fast  /usr/bin/sudoedit
../subjects/md5sum.fast  /usr/bin/sudoreplay
../subjects/md5sum.fast  /usr/bin/sum
../subjects/md5sum.fast  /usr/bin/symcryptrun
../subjects/md5sum.fast  /usr/bin/synclient
../subjects/md5sum.fast  /usr/bin/syndaemon
../subjects/md5sum.fast  /usr/bin/system-config-printer
../subjects/md5sum.fast  /usr/bin/system-config-printer-applet
../subjects/md5sum.fast  /usr/bin/systemd-analyze
../subjects/md5sum.fast  /usr/bin/systemd-cat
../subjects/md5sum.fast  /usr/bin/systemd-cgls
../subjects/md5sum.fast  /usr/bin/systemd-cgtop
../subjects/md5sum.fast  /usr/bin/systemd-delta
../subjects/md5sum.fast  /usr/bin/systemd-detect-virt
../subjects/md5sum.fast  /usr/bin/systemd-path
../subjects/md5sum.fast  /usr/bin/systemd-resolve
../subjects/md5sum.fast  /usr/bin/systemd-run
../subjects/md5sum.fast  /usr/bin/systemd-stdio-bridge
../subjects/md5sum.fast  /usr/bin/t1ascii
../subjects/md5sum.fast  /usr/bin/t1asm
../subjects/md5sum.fast  /usr/bin/t1binary
../subjects/md5sum.fast  /usr/bin/t1disasm
../subjects/md5sum.fast  /usr/bin/t1mac
../subjects/md5sum.fast  /usr/bin/t1unmac
../subjects/md5sum.fast  /usr/bin/tabs
../subjects/md5sum.fast  /usr/bin/tac
../subjects/md5sum.fast  /usr/bin/tail
../subjects/md5sum.fast  /usr/bin/tapestat
../subjects/md5sum.fast  /usr/bin/tasksel
../subjects/md5sum.fast  /usr/bin/taskset
../subjects/md5sum.fast  /usr/bin/tbl
../subjects/md5sum.fast  /usr/bin/tdbbackup
../subjects/md5sum.fast  /usr/bin/tdbbackup.tdbtools
../subjects/md5sum.fast  /usr/bin/tdbdump
../subjects/md5sum.fast  /usr/bin/tdbrestore
../subjects/md5sum.fast  /usr/bin/tdbtool
../subjects/md5sum.fast  /usr/bin/tee
../subjects/md5sum.fast  /usr/bin/telnet
../subjects/md5sum.fast  /usr/bin/telnet.netkit
../subjects/md5sum.fast  /usr/bin/test
../subjects/md5sum.fast  /usr/bin/testparm
../subjects/md5sum.fast  /usr/bin/texi2any
../subjects/md5sum.fast  /usr/bin/texi2dvi
../subjects/md5sum.fast  /usr/bin/texi2pdf
../subjects/md5sum.fast  /usr/bin/texindex
../subjects/md5sum.fast  /usr/bin/tic
../subjects/md5sum.fast  /usr/bin/time
../subjects/md5sum.fast  /usr/bin/timedatectl
../subjects/md5sum.fast  /usr/bin/timeout
../subjects/md5sum.fast  /usr/bin/tload
../subjects/md5sum.fast  /usr/bin/tmux
../subjects/md5sum.fast  /usr/bin/tnameserv
../subjects/md5sum.fast  /usr/bin/toe
../subjects/md5sum.fast  /usr/bin/top
../subjects/md5sum.fast  /usr/bin/touch
../subjects/md5sum.fast  /usr/bin/tput
../subjects/md5sum.fast  /usr/bin/tr
../subjects/md5sum.fast  /usr/bin/tracepath
../subjects/md5sum.fast  /usr/bin/tracepath6
../subjects/md5sum.fast  /usr/bin/traceroute6
../subjects/md5sum.fast  /usr/bin/traceroute6.iputils
../subjects/md5sum.fast  /usr/bin/troff
../subjects/md5sum.fast  /usr/bin/truncate
../subjects/md5sum.fast  /usr/bin/trust
../subjects/md5sum.fast  /usr/bin/tset
../subjects/md5sum.fast  /usr/bin/tsort
../subjects/md5sum.fast  /usr/bin/tty
../subjects/md5sum.fast  /usr/bin/turbostat
../subjects/md5sum.fast  /usr/bin/txixml2texi
../subjects/md5sum.fast  /usr/bin/tzselect
../subjects/md5sum.fast  /usr/bin/ubuntu-advantage
../subjects/md5sum.fast  /usr/bin/ubuntu-bug
../subjects/md5sum.fast  /usr/bin/ubuntu-core-launcher
../subjects/md5sum.fast  /usr/bin/ubuntu-support-status
../subjects/md5sum.fast  /usr/bin/ucf
../subjects/md5sum.fast  /usr/bin/ucfq
../subjects/md5sum.fast  /usr/bin/ucfr
../subjects/md5sum.fast  /usr/bin/ucs2any
../subjects/md5sum.fast  /usr/bin/udisksctl
../subjects/md5sum.fast  /usr/bin/ul
../subjects/md5sum.fast  /usr/bin/unattended-upgrade
../subjects/md5sum.fast  /usr/bin/unattended-upgrades
../subjects/md5sum.fast  /usr/bin/unexpand
../subjects/md5sum.fast  /usr/bin/unicode_stop
../subjects/md5sum.fast  /usr/bin/uniq
../subjects/md5sum.fast  /usr/bin/unity-control-center
../subjects/md5sum.fast  /usr/bin/unity-settings-daemon
../subjects/md5sum.fast  /usr/bin/unlink
../subjects/md5sum.fast  /usr/bin/unlzma
../subjects/md5sum.fast  /usr/bin/unpack200
../subjects/md5sum.fast  /usr/bin/unpigz
../subjects/md5sum.fast  /usr/bin/unshare
../subjects/md5sum.fast  /usr/bin/unsquashfs
../subjects/md5sum.fast  /usr/bin/unwrapdiff
../subjects/md5sum.fast  /usr/bin/unxz
../subjects/md5sum.fast  /usr/bin/unzip
../subjects/md5sum.fast  /usr/bin/unzipsfx
../subjects/md5sum.fast  /usr/bin/update-alternatives
../subjects/md5sum.fast  /usr/bin/updatedb
../subjects/md5sum.fast  /usr/bin/updatedb.mlocate
../subjects/md5sum.fast  /usr/bin/update-desktop-database
../subjects/md5sum.fast  /usr/bin/update-gconf-defaults
../subjects/md5sum.fast  /usr/bin/update-mime-database
../subjects/md5sum.fast  /usr/bin/update-mime-database.real
../subjects/md5sum.fast  /usr/bin/update-perl-sax-parsers
../subjects/md5sum.fast  /usr/bin/upower
../subjects/md5sum.fast  /usr/bin/uptime
../subjects/md5sum.fast  /usr/bin/usb-devices
../subjects/md5sum.fast  /usr/bin/usbhid-dump
../subjects/md5sum.fast  /usr/bin/usbip
../subjects/md5sum.fast  /usr/bin/usbipd
../subjects/md5sum.fast  /usr/bin/users
../subjects/md5sum.fast  /usr/bin/utmpdump
../subjects/md5sum.fast  /usr/bin/uuidgen
../subjects/md5sum.fast  /usr/bin/vacuumdb
../subjects/md5sum.fast  /usr/bin/vacuumlo
../subjects/md5sum.fast  /usr/bin/vcs-run
../subjects/md5sum.fast  /usr/bin/VGAuthService
../subjects/md5sum.fast  /usr/bin/vi
../subjects/md5sum.fast  /usr/bin/view
../subjects/md5sum.fast  /usr/bin/viewres
../subjects/md5sum.fast  /usr/bin/vigpg
../subjects/md5sum.fast  /usr/bin/vim
../subjects/md5sum.fast  /usr/bin/vim.basic
../subjects/md5sum.fast  /usr/bin/vimdiff
../subjects/md5sum.fast  /usr/bin/vim.tiny
../subjects/md5sum.fast  /usr/bin/vimtutor
../subjects/md5sum.fast  /usr/bin/virtualenv
../subjects/md5sum.fast  /usr/bin/vmhgfs-fuse
../subjects/md5sum.fast  /usr/bin/vmstat
../subjects/md5sum.fast  /usr/bin/vmtoolsd
../subjects/md5sum.fast  /usr/bin/vmware-checkvm
../subjects/md5sum.fast  /usr/bin/vmware-guestproxycerttool
../subjects/md5sum.fast  /usr/bin/vmware-hgfsclient
../subjects/md5sum.fast  /usr/bin/vmware-namespace-cmd
../subjects/md5sum.fast  /usr/bin/vmware-rpctool
../subjects/md5sum.fast  /usr/bin/vmware-toolbox-cmd
../subjects/md5sum.fast  /usr/bin/vmware-user
../subjects/md5sum.fast  /usr/bin/vmware-vgauth-cmd
../subjects/md5sum.fast  /usr/bin/vmware-vgauth-smoketest
../subjects/md5sum.fast  /usr/bin/vmware-vmblock-fuse
../subjects/md5sum.fast  /usr/bin/vmware-xferlogs
../subjects/md5sum.fast  /usr/bin/volname
../subjects/md5sum.fast  /usr/bin/w
../subjects/md5sum.fast  /usr/bin/wall
../subjects/md5sum.fast  /usr/bin/watch
../subjects/md5sum.fast  /usr/bin/wbinfo
../subjects/md5sum.fast  /usr/bin/wc
../subjects/md5sum.fast  /usr/bin/wget
../subjects/md5sum.fast  /usr/bin/whatis
../subjects/md5sum.fast  /usr/bin/whereis
../subjects/md5sum.fast  /usr/bin/which
../subjects/md5sum.fast  /usr/bin/who
../subjects/md5sum.fast  /usr/bin/whoami
../subjects/md5sum.fast  /usr/bin/wifi-status
../subjects/md5sum.fast  /usr/bin/word-list-compress
../subjects/md5sum.fast  /usr/bin/wpa_passphrase
../subjects/md5sum.fast  /usr/bin/w.procps
../subjects/md5sum.fast  /usr/bin/write
../subjects/md5sum.fast  /usr/bin/wsgen
../subjects/md5sum.fast  /usr/bin/wsimport
../subjects/md5sum.fast  /usr/bin/wx-config
../subjects/md5sum.fast  /usr/bin/wxrc
../subjects/md5sum.fast  /usr/bin/X
../subjects/md5sum.fast  /usr/bin/X11
../subjects/md5sum.fast  /usr/bin/x86_64
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-addr2line
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-ar
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-as
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-c++filt
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-cpp
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-cpp-3.4
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-cpp-4.4
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-cpp-4.7
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-cpp-5
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-dwp
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-elfedit
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-g++
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-g++-4.4
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-g++-4.7
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-g++-5
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-gcc
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-gcc-4.4
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-gcc-4.7
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-gcc-5
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-gcc-ar
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-gcc-ar-4.7
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-gcc-ar-5
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-gcc-nm
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-gcc-nm-4.7
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-gcc-nm-5
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-gcc-ranlib
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-gcc-ranlib-4.7
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-gcc-ranlib-5
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-gcov
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-gcov-5
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-gcov-tool
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-gcov-tool-5
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-gprof
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-ld
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-ld.bfd
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-ld.gold
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-nm
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-objcopy
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-objdump
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-pkg-config
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-python3.5-config
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-python3.5m-config
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-python3-config
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-python3m-config
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-ranlib
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-readelf
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-size
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-strings
../subjects/md5sum.fast  /usr/bin/x86_64-linux-gnu-strip
../subjects/md5sum.fast  /usr/bin/x86_64-pc-linux-gnu-pkg-config
../subjects/md5sum.fast  /usr/bin/x86_energy_perf_policy
../subjects/md5sum.fast  /usr/bin/xargs
../subjects/md5sum.fast  /usr/bin/xauth
../subjects/md5sum.fast  /usr/bin/xdg-user-dir
../subjects/md5sum.fast  /usr/bin/xdg-user-dirs-update
../subjects/md5sum.fast  /usr/bin/xdpyinfo
../subjects/md5sum.fast  /usr/bin/xdriinfo
../subjects/md5sum.fast  /usr/bin/xev
../subjects/md5sum.fast  /usr/bin/xfd
../subjects/md5sum.fast  /usr/bin/xfontsel
../subjects/md5sum.fast  /usr/bin/xgettext
../subjects/md5sum.fast  /usr/bin/xjc
../subjects/md5sum.fast  /usr/bin/xkbbell
../subjects/md5sum.fast  /usr/bin/xkbcomp
../subjects/md5sum.fast  /usr/bin/xkbevd
../subjects/md5sum.fast  /usr/bin/xkbprint
../subjects/md5sum.fast  /usr/bin/xkbvleds
../subjects/md5sum.fast  /usr/bin/xkbwatch
../subjects/md5sum.fast  /usr/bin/xkill
../subjects/md5sum.fast  /usr/bin/xlsatoms
../subjects/md5sum.fast  /usr/bin/xlsclients
../subjects/md5sum.fast  /usr/bin/xlsfonts
../subjects/md5sum.fast  /usr/bin/xmessage
../subjects/md5sum.fast  /usr/bin/Xorg
../subjects/md5sum.fast  /usr/bin/xprop
../subjects/md5sum.fast  /usr/bin/x-session-manager
../subjects/md5sum.fast  /usr/bin/xsetwacom
../subjects/md5sum.fast  /usr/bin/xsubpp
../subjects/md5sum.fast  /usr/bin/xvinfo
../subjects/md5sum.fast  /usr/bin/xwininfo
../subjects/md5sum.fast  /usr/bin/xxd
../subjects/md5sum.fast  /usr/bin/xz
../subjects/md5sum.fast  /usr/bin/xzcat
../subjects/md5sum.fast  /usr/bin/xzcmp
../subjects/md5sum.fast  /usr/bin/xzdiff
../subjects/md5sum.fast  /usr/bin/xzegrep
../subjects/md5sum.fast  /usr/bin/xzfgrep
../subjects/md5sum.fast  /usr/bin/xzgrep
../subjects/md5sum.fast  /usr/bin/xzless
../subjects/md5sum.fast  /usr/bin/xzmore
../subjects/md5sum.fast  /usr/bin/yacc
../subjects/md5sum.fast  /usr/bin/yelp
../subjects/md5sum.fast  /usr/bin/yes
../subjects/md5sum.fast  /usr/bin/zdump
../subjects/md5sum.fast  /usr/bin/zip
../subjects/md5sum.fast  /usr/bin/zipcloak
../subjects/md5sum.fast  /usr/bin/zipdetails
../subjects/md5sum.fast  /usr/bin/zipgrep
../subjects/md5sum.fast  /usr/bin/zipinfo
../subjects/md5sum.fast  /usr/bin/zipnote
../subjects/md5sum.fast  /usr/bin/zipsplit
