../subjects/md5sum.fast /usr/bin/apt
../subjects/md5sum.fast /usr/bin/ar
../subjects/md5sum.fast /usr/bin/gcc
../subjects/md5sum.fast /usr/bin/vi
../subjects/md5sum.fast /usr/bin/ldd
../subjects/md5sum.fast /usr/bin/ld
../subjects/md5sum.fast /usr/bin/wget
../subjects/md5sum.fast /usr/bin/which
../subjects/md5sum.fast /usr/bin/clear
../subjects/md5sum.fast /usr/bin/curl
